function fmtPct(n) { return n.toFixed(1) + "%"; }
function fmtUsd(n) { return "$" + n.toFixed(2); }

const CHATBOT_INTENTS = [
  {
    test: /why.*russia|russia.*why/i,
    answer: () => {
      const r = CURRENT.result;
      const bpd = r.bySource.russia || 0;
      return `Russia is capped at 35% of total demand (the concentration limit), which is ${fmtBpd(2370000 * 0.35)} bpd. At the current scenario it's supplying ${fmtBpd(bpd)} bpd. It's consistently the cheapest non-Hormuz source, so the optimizer fills it to the cap first whenever Hormuz risk rises, before spreading the remaining gap across Venezuela, Brazil, Nigeria, and the US.`;
    },
  },
  {
    test: /full(y)?\s*clos|100%|completely closed|worst case/i,
    answer: () => {
      const r = solve({ hormuz: 1.0 });
      const hormuzSources = ["saudi_arabia", "iraq", "uae", "kuwait"];
      const hpct = (100 * hormuzSources.reduce((a, s) => a + (r.bySource[s] || 0), 0)) / r.totalBpd;
      return `At a full, 100% Hormuz closure, the model still meets ${fmtPct(r.fulfillmentPct)} of refinery demand. Landed cost rises to ${fmtUsd(r.avgCostPerBbl)}/bbl, and Hormuz-linked sourcing falls to ${fmtPct(hpct)} of total. This is the key finding: even total closure is a cost and routing problem, not a volume crisis, because global spare capacity outside the Gulf is large enough to absorb it.`;
    },
  },
  {
    test: /confiden|sure|certain|trust/i,
    answer: () => {
      const e = CURRENT.event;
      const conf = e.confidence !== undefined ? Math.round(e.confidence * 100) : null;
      if (conf === null) return "This is a user-defined custom scenario, so it's treated at full confidence by construction. Switch to backtest mode to see how the model handles contested, lower-confidence signals like June 20th.";
      if (conf < 50) return `Confidence on this specific signal is only ${conf}%. ${e.conflict ? "It's flagged as contested because multiple sources disagreed on the same day." : ""} The memo explicitly recommends rechecking within 24 hours rather than treating the recommendation as final.`;
      return `Confidence on this signal is ${conf}%, drawn from ${e.source}. Confidence only affects how strongly the memo qualifies its language, it doesn't change the optimizer's math, that always solves exactly given whatever shock level is passed in.`;
    },
  },
  {
    test: /reserve|spr|strategic petroleum/i,
    answer: () => {
      const res = CURRENT.reserves;
      if (!res.drawNeeded) return "At this disruption level, there's no meaningful Hormuz-linked reserve exposure, so no drawdown is modelled.";
      return `If this volume were not rerouted, the reserve would last ${res.daysOfCover} days against the gap, covering ${res.sufficient ? "more than" : "less than"} the 30-day window modelled. ${res.sufficient ? "" : "That's why the memo says reroute, not drawdown, is the primary lever, the reserve alone can't bridge this."}`;
    },
  },
  {
    test: /cost|price|expensive|dollar|\$/i,
    answer: () => {
      const r = CURRENT.result;
      return `Average landed cost right now is ${fmtUsd(r.avgCostPerBbl)} per barrel, versus ${fmtUsd(BASE.avgCostPerBbl)} at baseline, a difference of ${CURRENT.costDelta > 0 ? "+" : ""}${fmtUsd(CURRENT.costDelta)}. That's driven mostly by freight: disrupted corridors carry a cost penalty up to 3.5x the normal freight rate, which is why cost moves even when total volume doesn't.`;
    },
  },
  {
    test: /assum|model.*based|how.*work|methodology/i,
    answer: () =>
      "The core is a linear program: it minimizes total cost subject to source capacity, a 35% single-source concentration cap, a 92% refinery utilization floor, and grade-compatibility penalties. The corridor shock scales both available capacity and freight cost for that corridor. None of this is generated by a language model, the LLM layer only writes the memo explaining what the solver already computed.",
  },
  {
    test: /validat|accurate|real data|actually happened|kpler/i,
    answer: () =>
      "The model was checked against real June 2026 Kpler import data. Russia and Venezuela rank as the top two beneficiaries in both the model's output and what actually happened, that's a directional match, not an exact barrel-for-barrel match, since this is a single-snapshot solve rather than a rolling four-month model.",
  },
  {
    test: /grade|sour|sweet|refinery.*type|compatib/i,
    answer: () =>
      "Each refinery is built for certain crude grades, light sweet, medium sour, heavy sour, or medium sweet. Using the wrong grade at a refinery adds a cost penalty rather than being blocked outright, modelling the real efficiency loss of processing an off-spec crude. That's part of why some cheap sources don't get used as much as you'd expect from price alone.",
  },
  {
    test: /june\s*20|contest|conflict|irgc|centcom/i,
    answer: () =>
      "On June 20, 2026, Iran's military said Hormuz was closed, Iran's own foreign ministry said shipping was normal, and US CENTCOM reported 55 ships transited anyway, three contradicting claims, same day. The model handles this by treating the shock level as low-confidence (30%) and the memo explicitly flags the contested signal rather than presenting a single confident number.",
  },
  {
    test: /hi|hello|hey|help|what can you/i,
    answer: () =>
      "I can answer questions about the current scenario, try: \"why Russia?\", \"what if Hormuz fully closes?\", \"how confident is this?\", \"what about the reserve?\", or \"how does the model work?\". I read the live numbers on screen, so my answers change as you move the timeline or the shock slider.",
  },
];

const CHATBOT_FALLBACK = () => {
  const r = CURRENT.result;
  return `I don't have a scripted answer for that, but here's the current state: fulfillment ${fmtPct(r.fulfillmentPct)}, landed cost ${fmtUsd(r.avgCostPerBbl)}/bbl, Hormuz exposure ${fmtPct(CURRENT.hormuzPct)}. Try asking about Russia, the reserve, confidence, or what happens at full closure.`;
};

function chatbotRespond(text) {
  const match = CHATBOT_INTENTS.find((i) => i.test.test(text));
  if (match) return match.answer();
  return CHATBOT_FALLBACK();
}
